name: Gatsby Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.NEW_ACCESS_TOKEN }}
          deploy-branch: publish
          git-config-name: CyberSoc
          git-config-email: cyber@yusu.org
