name: Test Gatsby Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.NEW_ACCESS_TOKEN }}
          deploy-branch: main
          gatsby-args: --verbose
          skip-publish: true
